#!/usr/bin/env python3
"""Assemble paper/attachment/ — the folder to upload with the manuscript.

Copies only locked, paper-facing files. Does not move or delete source experiments.
"""

from __future__ import annotations

import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"
DEST = PAPER / "attachment"

FIGURES = [
    "fig01_system_architecture",
    "fig02_bloom_confusion_matrix",
    "fig03_fedavg_fedprox_learning_curves",
    "fig04_source_target_accuracy",
    "fig05_source_target_fully_validated",
    "fig06_multitask_task_performance",
    "fig07_gguf_deployment",
    "fig08_privacy_ablation",
]

TABLES = [
    "table1_datasets",
    "table2_bloom_classifier",
    "table2b_fedavg_vs_fedprox",
    "table3_classifier_size_selection",
    "table4_multitask_v3",
    "table5_source_target_extremes",
    "table6_role_privacy",
    "table7_gguf_deployment",
]

PROVENANCE = [
    "final_experiment_inventory.md",
    "final_validation_report.md",
    "paper_experiment_manifest.json",
    "validate_snapshot.json",
]

PROOFS = [
    "proofs/proof3_rag/proof3_rag_retrieval_report.md",
    "proofs/proof3_rag/proof3_rag_retrieval_report.json",
    "proofs/proof4_privacy/proof4_protected_content_report.md",
    "proofs/proof4_privacy/proof4_protected_content_report.json",
]


def _copy(src: Path, dst: Path, missing: list[str]) -> None:
    if not src.is_file():
        missing.append(str(src.relative_to(ROOT)))
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def main() -> None:
    if DEST.exists():
        shutil.rmtree(DEST)
    missing: list[str] = []

    for name in FIGURES:
        for ext in (".pdf", ".png"):
            _copy(PAPER / "figures" / f"{name}{ext}", DEST / "figures" / f"{name}{ext}", missing)

    for venue in ("ieee_openjournal", "elsevier"):
        for name in FIGURES:
            for ext in (".pdf", ".png"):
                _copy(
                    PAPER / "figures" / f"{name}{ext}",
                    DEST / "manuscripts" / venue / "figures" / f"{name}{ext}",
                    missing,
                )

    for stem in TABLES:
        for ext in (".tex", ".csv", ".md"):
            _copy(PAPER / "tables" / f"{stem}{ext}", DEST / "tables" / f"{stem}{ext}", missing)

    for name in PROVENANCE:
        _copy(PAPER / name, DEST / "provenance" / name, missing)

    for rel in PROOFS:
        _copy(PAPER / rel, DEST / "proofs" / Path(rel).name, missing)

    for venue in ("ieee_openjournal", "elsevier"):
        _copy(PAPER / venue / "manuscript.tex", DEST / "manuscripts" / venue / "manuscript.tex", missing)
        _copy(PAPER / venue / "references.bib", DEST / "manuscripts" / venue / "references.bib", missing)

    readme = DEST / "README.md"
    readme.write_text(
        """# EduGuard supplementary attachment

Upload this folder with the journal manuscript. It is generated by
`scripts/build_paper_attachment.py` from locked paper artifacts.
It does not contain model weights.

## What to submit

| Path | Role |
|------|------|
| `figures/` | Eight final figures (PDF and PNG) |
| `manuscripts/ieee_openjournal/` | IEEE source, bibliography, and a `figures/` folder so it compiles alone |
| `manuscripts/elsevier/` | Elsevier source, bibliography, and a `figures/` folder so it compiles alone |
| `tables/` | Final tables (LaTeX, CSV, Markdown) |
| `provenance/` | Experiment inventory, validation report, manifest |
| `proofs/` | RAG proof status (not paper-ready) and PrivacyGuard rates |

Submit **one** manuscript venue. Keep the other as an alternate source.
Figures and tables are identical for both.

## Figure order

1. `fig01_system_architecture.pdf` — system modules
2. `fig02_bloom_confusion_matrix.pdf` — selected FedProx classifier
3. `fig03_fedavg_fedprox_learning_curves.pdf` — 20-round IID
4. `fig04_source_target_accuracy.pdf` — rewrite target accuracy
5. `fig05_source_target_fully_validated.pdf` — fully validated rate
6. `fig06_multitask_task_performance.pdf` — rewrite / QA / summarization
7. `fig07_gguf_deployment.pdf` — Q4_K_M micro-benchmark
8. `fig08_privacy_ablation.pdf` — attack block vs benign allow

## Do not attach from elsewhere in the repo

- Pre-v3 multitask result folders (`qwen05b_lora`, `qwen15b_lora`, `qwen15b_lora_sumfix`)
- `unified_results_table` accuracy 0.840 (no backing metrics file; use 0.8314)
- Human-eval files (ratings are empty)
- Smoke RAG CSV as if it were Recall@5 / MRR
- Model weight directories (`models/`, federated adapters)

## Rebuild

```bash
python scripts/build_paper_attachment.py
```
""",
        encoding="utf-8",
    )

    lines = [
        f"# Attachment file list",
        f"",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        f"",
    ]
    for path in sorted(DEST.rglob("*")):
        if path.is_file():
            rel = path.relative_to(DEST).as_posix()
            lines.append(f"- `{rel}` ({path.stat().st_size} bytes)")
    if missing:
        lines.append("")
        lines.append("## Missing sources")
        for item in missing:
            lines.append(f"- {item}")
    (DEST / "FILE_LIST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[attachment] wrote {DEST}")
    print(f"[attachment] missing={len(missing)}")
    for item in missing:
        print(f"  MISSING {item}")
    if missing:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
